# Generated by Django 4.2.7 on 2026-06-17 18:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIProcessingQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_id', models.UUIDField(db_index=True)),
                ('stage', models.CharField(choices=[('queued', 'Queued'), ('ocr', 'OCR Processing'), ('text_extraction', 'Text Extraction'), ('text_cleaning', 'Text Cleaning'), ('classification', 'Classification'), ('metadata', 'Metadata Generation'), ('summary', 'Summary Generation'), ('embedding', 'Embedding Generation'), ('storing', 'Storing Vectors'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=30)),
                ('progress', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_processing_queue',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentClassification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_id', models.UUIDField(db_index=True, unique=True)),
                ('category', models.CharField(choices=[('invoice', 'Invoice'), ('contract', 'Contract'), ('tax_filing', 'Tax Filing'), ('medical_record', 'Medical Record'), ('bank_statement', 'Bank Statement'), ('legal_agreement', 'Legal Agreement'), ('insurance_policy', 'Insurance Policy'), ('audit_report', 'Audit Report'), ('certificate', 'Certificate'), ('purchase_order', 'Purchase Order'), ('employee_record', 'Employee Record'), ('vendor_agreement', 'Vendor Agreement'), ('business_license', 'Business License'), ('compliance_report', 'Compliance Report'), ('other', 'Other')], default='other', max_length=50)),
                ('subcategory', models.CharField(blank=True, max_length=100)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('confidentiality', models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('confidential', 'Confidential'), ('restricted', 'Restricted')], default='internal', max_length=20)),
                ('risk_score', models.FloatField(default=0.0)),
                ('ai_model_version', models.CharField(default='avora-v2', max_length=50)),
                ('raw_response', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'document_classifications',
            },
        ),
        migrations.CreateModel(
            name='DocumentEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.UUIDField(db_index=True, unique=True)),
                ('qdrant_point_id', models.UUIDField(unique=True)),
                ('model_name', models.CharField(default='nomic-embed-text', max_length=100)),
                ('vector_size', models.IntegerField(default=768)),
                ('text_chunk_count', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'document_embeddings',
            },
        ),
        migrations.CreateModel(
            name='DocumentMetadataAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.UUIDField(db_index=True, unique=True)),
                ('vendor', models.CharField(blank=True, max_length=255)),
                ('client', models.CharField(blank=True, max_length=255)),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('document_date', models.DateField(blank=True, null=True)),
                ('year', models.CharField(blank=True, max_length=10)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('currency', models.CharField(blank=True, max_length=10)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('keywords', models.JSONField(default=list)),
                ('entities', models.JSONField(default=dict)),
                ('extra_fields', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'document_metadata_ai',
            },
        ),
        migrations.CreateModel(
            name='DocumentOCR',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_id', models.UUIDField(db_index=True, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('raw_text', models.TextField(blank=True)),
                ('cleaned_text', models.TextField(blank=True)),
                ('page_count', models.IntegerField(default=0)),
                ('word_count', models.IntegerField(default=0)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('engine_used', models.CharField(default='paddleocr', max_length=50)),
                ('language', models.CharField(default='en', max_length=20)),
                ('processing_ms', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'document_ocr',
            },
        ),
        migrations.CreateModel(
            name='DocumentRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.UUIDField(db_index=True)),
                ('recommended_document_id', models.UUIDField(db_index=True)),
                ('score', models.FloatField(default=0.0)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'document_recommendations',
                'ordering': ['-score'],
            },
        ),
        migrations.CreateModel(
            name='DocumentRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_document_id', models.UUIDField(db_index=True)),
                ('target_document_id', models.UUIDField(db_index=True)),
                ('relationship_type', models.CharField(choices=[('revision', 'Revision / Updated Version'), ('duplicate', 'Potential Duplicate'), ('related', 'Related Document'), ('parent', 'Parent Document'), ('child', 'Child Document'), ('reference', 'Referenced Document')], max_length=20)),
                ('similarity_score', models.FloatField(default=0.0)),
                ('ai_confidence', models.FloatField(default=0.0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'document_relationships',
            },
        ),
        migrations.CreateModel(
            name='DocumentSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.UUIDField(db_index=True, unique=True)),
                ('short_summary', models.CharField(blank=True, max_length=300)),
                ('medium_summary', models.TextField(blank=True)),
                ('long_summary', models.TextField(blank=True)),
                ('key_points', models.JSONField(default=list)),
                ('model_used', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'document_summaries',
            },
        ),
        migrations.CreateModel(
            name='DocumentTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.UUIDField(db_index=True)),
                ('tag', models.CharField(max_length=100)),
                ('source', models.CharField(default='ai', max_length=20)),
                ('confidence', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'document_tags',
                'ordering': ['-confidence'],
            },
        ),
        migrations.CreateModel(
            name='SearchAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=500, unique=True)),
                ('search_count', models.IntegerField(default=0)),
                ('avg_results', models.FloatField(default=0.0)),
                ('avg_score', models.FloatField(default=0.0)),
                ('last_searched', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'search_analytics',
                'ordering': ['-search_count'],
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query', models.CharField(max_length=500)),
                ('result_count', models.IntegerField(default=0)),
                ('top_result_id', models.UUIDField(blank=True, null=True)),
                ('filters', models.JSONField(default=dict)),
                ('search_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'search_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SmartCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='folder', max_length=50)),
                ('color', models.CharField(default='blue', max_length=20)),
                ('collection_type', models.CharField(choices=[('ai_generated', 'AI Generated'), ('user_created', 'User Created')], default='ai_generated', max_length=20)),
                ('category_filter', models.CharField(blank=True, max_length=50)),
                ('rules', models.JSONField(default=dict)),
                ('document_count', models.IntegerField(default=0)),
                ('is_auto_updated', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'smart_collections',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SmartCollectionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.UUIDField(db_index=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('relevance', models.FloatField(default=1.0)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ai.smartcollection')),
            ],
            options={
                'db_table': 'smart_collection_documents',
            },
        ),
    ]
