# Generated by Django 4.2.7 on 2026-06-17 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartcollection',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smart_collections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='documenttag',
            unique_together={('document_id', 'tag')},
        ),
        migrations.AlterUniqueTogether(
            name='documentrelationship',
            unique_together={('source_document_id', 'target_document_id')},
        ),
        migrations.AddIndex(
            model_name='aiprocessingqueue',
            index=models.Index(fields=['document_id'], name='ai_processi_documen_957b67_idx'),
        ),
        migrations.AddIndex(
            model_name='aiprocessingqueue',
            index=models.Index(fields=['stage'], name='ai_processi_stage_b4bb2b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='smartcollectiondocument',
            unique_together={('collection', 'document_id')},
        ),
    ]
