# Generated by Django 4.2.7 on 2026-06-17 18:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('node_type', models.CharField(choices=[('vendor', 'Vendor'), ('customer', 'Customer'), ('employee', 'Employee'), ('contract', 'Contract'), ('invoice', 'Invoice'), ('certificate', 'Certificate'), ('policy', 'Policy'), ('department', 'Department'), ('project', 'Project'), ('document', 'Document')], max_length=20)),
                ('document_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('properties', models.JSONField(default=dict)),
                ('embedding_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'knowledge_nodes',
                'ordering': ['node_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship_type', models.CharField(choices=[('signed_by', 'Signed By'), ('issued_to', 'Issued To'), ('related_to', 'Related To'), ('parent_of', 'Parent Of'), ('belongs_to', 'Belongs To'), ('created_by', 'Created By'), ('approved_by', 'Approved By'), ('linked_to', 'Linked To'), ('references', 'References'), ('supersedes', 'Supersedes')], max_length=20)),
                ('confidence', models.FloatField(default=0.9)),
                ('properties', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing', to='knowledge.knowledgenode')),
                ('target_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming', to='knowledge.knowledgenode')),
            ],
            options={
                'db_table': 'knowledge_relationships',
            },
        ),
    ]
