# Generated by Django 4.2.7 on 2026-07-08 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('google_drive', 'Google Drive'), ('onedrive', 'Microsoft OneDrive'), ('sharepoint', 'Microsoft SharePoint'), ('dropbox', 'Dropbox'), ('slack', 'Slack'), ('notion', 'Notion')], max_length=30)),
                ('_client_id', models.TextField(blank=True, db_column='client_id_enc')),
                ('_client_secret', models.TextField(blank=True, db_column='client_secret_enc')),
                ('_access_token', models.TextField(blank=True, db_column='access_token_enc')),
                ('_refresh_token', models.TextField(blank=True, db_column='refresh_token_enc')),
                ('google_user_id', models.CharField(blank=True, max_length=100)),
                ('google_email', models.CharField(blank=True, max_length=200)),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('connected', 'Connected'), ('syncing', 'Syncing'), ('error', 'Error'), ('disconnected', 'Disconnected')], default='pending', max_length=20)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('sync_error', models.TextField(blank=True)),
                ('files_indexed', models.IntegerField(default=0)),
                ('selected_folders', models.JSONField(default=list)),
                ('folder_names', models.JSONField(default=dict)),
                ('sync_permissions', models.BooleanField(default=True)),
                ('allowed_users', models.JSONField(default=list)),
                ('allowed_groups', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'integration_configs',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'provider')},
            },
        ),
        migrations.CreateModel(
            name='SyncEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=30)),
                ('file_id', models.CharField(blank=True, max_length=200)),
                ('file_name', models.CharField(blank=True, max_length=500)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_events', to='integrations.integrationconfig')),
            ],
            options={
                'db_table': 'integration_sync_events',
                'ordering': ['-created_at'],
            },
        ),
    ]
