# Generated by Django 4.2.7 on 2026-07-08 17:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationconfig',
            name='provider',
            field=models.CharField(choices=[('google_drive', 'Google Drive'), ('github', 'GitHub'), ('onedrive', 'Microsoft OneDrive'), ('sharepoint', 'Microsoft SharePoint'), ('dropbox', 'Dropbox'), ('slack', 'Slack'), ('notion', 'Notion')], max_length=30),
        ),
        migrations.CreateModel(
            name='GitHubIntegrationConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('github_user_id', models.CharField(blank=True, max_length=50)),
                ('github_login', models.CharField(blank=True, max_length=150)),
                ('github_email', models.CharField(blank=True, max_length=200)),
                ('github_name', models.CharField(blank=True, max_length=255)),
                ('github_avatar_url', models.URLField(blank=True)),
                ('github_org', models.CharField(blank=True, max_length=150)),
                ('selected_repos', models.JSONField(default=list)),
                ('repo_permissions', models.JSONField(default=dict)),
                ('sync_source_code', models.BooleanField(default=True)),
                ('sync_pull_requests', models.BooleanField(default=True)),
                ('sync_issues', models.BooleanField(default=True)),
                ('sync_commits', models.BooleanField(default=True)),
                ('sync_docs', models.BooleanField(default=True)),
                ('sync_wiki', models.BooleanField(default=False)),
                ('sync_workflows', models.BooleanField(default=True)),
                ('sync_releases', models.BooleanField(default=True)),
                ('sync_security', models.BooleanField(default=True)),
                ('sync_discussions', models.BooleanField(default=False)),
                ('total_code_chunks', models.IntegerField(default=0)),
                ('total_prs_indexed', models.IntegerField(default=0)),
                ('total_issues_indexed', models.IntegerField(default=0)),
                ('total_commits_indexed', models.IntegerField(default=0)),
                ('total_docs_indexed', models.IntegerField(default=0)),
                ('graph_built_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='github_config', to='integrations.integrationconfig')),
            ],
            options={
                'db_table': 'github_integration_configs',
            },
        ),
    ]
