# Generated by Django 4.2.7 on 2026-06-17 18:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_name', models.CharField(max_length=500)),
                ('storage_key', models.CharField(max_length=500, unique=True)),
                ('file_extension', models.CharField(max_length=20)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('original_size', models.BigIntegerField(default=0)),
                ('compressed_size', models.BigIntegerField(default=0)),
                ('encrypted_size', models.BigIntegerField(default=0)),
                ('total_chunks', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('processing', 'Processing'), ('encrypted', 'Encrypted'), ('ai_ready', 'AI Ready'), ('failed', 'Failed')], default='uploading', max_length=20)),
                ('version', models.IntegerField(default=1)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.IntegerField()),
                ('storage_key', models.CharField(max_length=500)),
                ('chunk_size', models.BigIntegerField()),
                ('sha256_hash', models.CharField(max_length=64)),
                ('iv', models.CharField(max_length=32)),
                ('tag', models.CharField(max_length=32)),
                ('upload_status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'document_chunks',
                'ordering': ['chunk_index'],
            },
        ),
        migrations.CreateModel(
            name='DocumentEncryptionKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_aes_key', models.BinaryField()),
                ('rsa_public_key_ref', models.CharField(max_length=200)),
                ('algorithm', models.CharField(default='AES-256-GCM', max_length=50)),
                ('key_derivation', models.CharField(default='RSA-OAEP-SHA256', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'document_encryption_keys',
            },
        ),
        migrations.CreateModel(
            name='DocumentMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('year', models.CharField(blank=True, max_length=10)),
                ('tags', models.JSONField(default=list)),
                ('ai_summary', models.TextField(blank=True)),
                ('page_count', models.IntegerField(default=0)),
                ('language', models.CharField(blank=True, default='en', max_length=50)),
                ('extra', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'document_metadata',
            },
        ),
        migrations.CreateModel(
            name='DocumentShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='documents.document')),
            ],
            options={
                'db_table': 'document_shares',
            },
        ),
    ]
