# Generated by Django 4.2.7 on 2026-07-05 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.IntegerField()),
                ('raw_text', models.TextField(blank=True)),
                ('storage_key', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_versions', to='documents.document')),
            ],
            options={
                'db_table': 'document_versions',
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChangeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ai_summary', models.TextField(blank=True, help_text='What changed')),
                ('ai_risk', models.TextField(blank=True, help_text='Risk introduced')),
                ('ai_compliance', models.TextField(blank=True, help_text='Compliance impact')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='documents.document')),
                ('from_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes_from', to='documents.documentversion')),
                ('to_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes_to', to='documents.documentversion')),
            ],
            options={
                'db_table': 'document_change_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
