# Generated by Django 4.2.7 on 2026-06-17 18:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('action', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('document_ids', models.JSONField(default=list)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('is_actioned', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_recommendations',
                'ordering': ['priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('report_type', models.CharField(choices=[('vendor_compliance', 'Vendor Compliance Report'), ('audit_evidence', 'Audit Evidence Package'), ('contract_summary', 'Contract Summary'), ('risk_assessment', 'Risk Assessment'), ('hr_review', 'HR Document Review'), ('financial_summary', 'Financial Summary'), ('compliance_gap', 'Compliance Gap Analysis'), ('custom', 'Custom Report')], default='custom', max_length=30)),
                ('status', models.CharField(choices=[('generating', 'Generating'), ('ready', 'Ready'), ('failed', 'Failed')], default='generating', max_length=15)),
                ('prompt_used', models.TextField(blank=True)),
                ('executive_summary', models.TextField(blank=True)),
                ('full_content', models.TextField(blank=True)),
                ('doc_count', models.IntegerField(default=0)),
                ('document_ids', models.JSONField(default=list)),
                ('key_findings', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('export_url', models.CharField(blank=True, max_length=500)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CopilotConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('mode', models.CharField(choices=[('document', 'Document Assistant'), ('compliance', 'Compliance Assistant'), ('audit', 'Audit Assistant'), ('knowledge', 'Knowledge Assistant'), ('risk', 'Risk Assistant')], default='document', max_length=20)),
                ('message_count', models.IntegerField(default=0)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'copilot_conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CopilotMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=10)),
                ('content', models.TextField()),
                ('thinking', models.TextField(blank=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('sources_count', models.IntegerField(default=0)),
                ('tokens_used', models.IntegerField(default=0)),
                ('latency_ms', models.IntegerField(default=0)),
                ('is_error', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'copilot_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_id', models.UUIDField(db_index=True)),
                ('document_name', models.CharField(max_length=500)),
                ('relevance', models.FloatField(default=0.0)),
                ('page_hint', models.CharField(blank=True, max_length=50)),
                ('excerpt', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'document_references',
                'ordering': ['-relevance'],
            },
        ),
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('prompt', models.TextField()),
                ('category', models.CharField(choices=[('audit', 'Audit Review'), ('contract', 'Contract Review'), ('vendor', 'Vendor Analysis'), ('policy', 'Policy Review'), ('risk', 'Risk Assessment'), ('compliance', 'Compliance Check'), ('financial', 'Financial Review'), ('hr', 'HR Review'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('is_builtin', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
                ('use_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'prompt_templates',
                'ordering': ['-use_count', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ReasoningLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query_analysis', models.TextField(blank=True)),
                ('retrieval_query', models.TextField(blank=True)),
                ('docs_retrieved', models.IntegerField(default=0)),
                ('context_tokens', models.IntegerField(default=0)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('hallucination_flags', models.JSONField(default=list)),
                ('guardrails_triggered', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reasoning', to='copilot.copilotmessage')),
            ],
            options={
                'db_table': 'reasoning_logs',
            },
        ),
    ]
