# Generated by Django 4.2.7 on 2026-06-17 18:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContractAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_id', models.UUIDField(db_index=True, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('party_a', models.CharField(blank=True, max_length=255)),
                ('party_b', models.CharField(blank=True, max_length=255)),
                ('contract_type', models.CharField(blank=True, max_length=100)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('auto_renewal', models.BooleanField(default=False)),
                ('notice_period_days', models.IntegerField(blank=True, null=True)),
                ('contract_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('currency', models.CharField(blank=True, max_length=10)),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('critical', 'Critical Risk')], default='low', max_length=10)),
                ('risk_score', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expiring', 'Expiring Soon'), ('expired', 'Expired'), ('draft', 'Draft'), ('terminated', 'Terminated')], default='active', max_length=15)),
                ('ai_summary', models.TextField(blank=True)),
                ('key_obligations', models.JSONField(default=list)),
                ('key_dates', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'contract_analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractRisk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('category', models.CharField(max_length=100)),
                ('recommendation', models.TextField(blank=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='contracts.contractanalysis')),
            ],
            options={
                'db_table': 'contract_risks',
                'ordering': ['-severity'],
            },
        ),
        migrations.CreateModel(
            name='ContractRenewal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('renewal_due', models.DateField()),
                ('notice_deadline', models.DateField(blank=True, null=True)),
                ('days_until', models.IntegerField(default=0)),
                ('action', models.CharField(choices=[('renew', 'Renew'), ('negotiate', 'Negotiate'), ('terminate', 'Terminate'), ('pending', 'Pending')], default='pending', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='renewal', to='contracts.contractanalysis')),
            ],
            options={
                'db_table': 'contract_renewals',
                'ordering': ['renewal_due'],
            },
        ),
        migrations.CreateModel(
            name='ContractClause',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clause_type', models.CharField(choices=[('termination', 'Termination'), ('renewal', 'Renewal'), ('payment', 'Payment Terms'), ('liability', 'Liability'), ('confidentiality', 'Confidentiality'), ('penalty', 'Penalty'), ('force_majeure', 'Force Majeure'), ('dispute', 'Dispute Resolution'), ('governing_law', 'Governing Law'), ('intellectual_prop', 'Intellectual Property'), ('non_compete', 'Non-Compete'), ('sla', 'SLA'), ('warranty', 'Warranty'), ('other', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('raw_text', models.TextField()),
                ('ai_summary', models.TextField(blank=True)),
                ('risk_flag', models.CharField(choices=[('green', 'No Risk'), ('yellow', 'Moderate Risk'), ('red', 'High Risk')], default='green', max_length=10)),
                ('risk_reason', models.TextField(blank=True)),
                ('is_standard', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='contracts.contractanalysis')),
            ],
            options={
                'db_table': 'contract_clauses',
            },
        ),
    ]
