# Generated by Django 4.2.7 on 2026-07-07 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#1A3DAF', help_text='Hex color for org-chart display', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent department for nested hierarchies', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='organizations.department')),
            ],
            options={
                'db_table': 'org_departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrgRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('level', models.PositiveIntegerField(default=5, help_text='1=highest, 10=lowest')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles', to='organizations.department')),
            ],
            options={
                'db_table': 'org_roles',
                'ordering': ['level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OrgMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='organizations.department')),
                ('manager', models.ForeignKey(blank=True, help_text='Immediate manager in the org tree', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='organizations.orgrole')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='org_member', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'org_members',
            },
        ),
        migrations.CreateModel(
            name='DocumentVisibility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_id', models.UUIDField(db_index=True, unique=True)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('user_share', 'User Share'), ('department', 'Department'), ('organization', 'Organization'), ('custom', 'Custom')], default='private', max_length=20)),
                ('inherit_upward', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_departments', models.ManyToManyField(blank=True, related_name='visible_docs', to='organizations.department')),
                ('allowed_roles', models.ManyToManyField(blank=True, related_name='visible_docs', to='organizations.orgrole')),
                ('allowed_users', models.ManyToManyField(blank=True, related_name='shared_with_me', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_visibility', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'document_visibility',
            },
        ),
    ]
