# Generated by Django 4.2.7 on 2026-06-17 18:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('generating', 'Generating'), ('ready', 'Ready'), ('failed', 'Failed')], default='generating', max_length=20)),
                ('doc_count', models.IntegerField(default=0)),
                ('document_ids', models.JSONField(default=list)),
                ('readiness_score', models.FloatField(default=0.0)),
                ('gaps', models.JSONField(default=list)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audit_packages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceCopilotChat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=10)),
                ('message', models.TextField()),
                ('context', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'compliance_copilot_chats',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('industry', models.CharField(choices=[('law_firm', 'Law Firm'), ('ca_firm', 'CA / Accounting'), ('healthcare', 'Healthcare'), ('consulting', 'Consulting'), ('startup', 'Startup'), ('other', 'Other')], default='other', max_length=30)),
                ('compliance_score', models.FloatField(default=0.0)),
                ('audit_readiness_pct', models.FloatField(default=0.0)),
                ('last_scored_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'compliance_profiles',
            },
        ),
        migrations.CreateModel(
            name='ComplianceTimeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(choices=[('filing_due', 'Filing Due'), ('renewal_due', 'Renewal Due'), ('audit_date', 'Audit Date'), ('license_expiry', 'License Expiry'), ('tax_due', 'Tax Due')], max_length=20)),
                ('due_date', models.DateField()),
                ('document_id', models.UUIDField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'compliance_timeline',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='ExpiryAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_id', models.UUIDField(db_index=True)),
                ('doc_name', models.CharField(max_length=500)),
                ('doc_type', models.CharField(max_length=100)),
                ('expiry_date', models.DateField()),
                ('alert_type', models.CharField(choices=[('expired', 'Expired'), ('expiring_30', 'Expires in 30 days'), ('expiring_60', 'Expires in 60 days'), ('expiring_90', 'Expires in 90 days')], max_length=20)),
                ('days_until', models.IntegerField(default=0)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'expiry_alerts',
                'ordering': ['expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='MissingDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('suggested_action', models.TextField(blank=True)),
                ('priority', models.CharField(default='high', max_length=10)),
                ('doc_type', models.CharField(blank=True, max_length=50)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'missing_documents',
                'ordering': ['priority', '-created_at'],
            },
        ),
    ]
