# Generated by Django 4.2.7 on 2026-06-17 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compliance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingdocument',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missing_docs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expiryalert',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expiry_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compliancetimeline',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_timeline', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complianceprofile',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compliancecopilotchat',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copilot_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditpackage',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_packages', to=settings.AUTH_USER_MODEL),
        ),
    ]
