# Generated by Django 4.2.7 on 2026-07-05 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compliance', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceRisk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_id', models.UUIDField(db_index=True)),
                ('doc_name', models.CharField(max_length=500)),
                ('compliance_standard', models.CharField(help_text='e.g., GDPR, SOC 2, ISO 27001, General', max_length=100)),
                ('risk_type', models.CharField(help_text='e.g., Missing Clause, Data Violation, Missing Signature', max_length=100)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('description', models.TextField()),
                ('suggested_fix', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_risks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'compliance_risks',
                'ordering': ['-created_at'],
            },
        ),
    ]
