# Generated by Django 4.2.7 on 2026-07-07 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compliance', '0003_compliancerisk'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceCheckResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_id', models.UUIDField(db_index=True)),
                ('doc_name', models.CharField(max_length=500)),
                ('requirement', models.CharField(help_text='e.g., GDPR, HIPAA, Encryption Clause', max_length=255)),
                ('status', models.CharField(help_text='Present or Missing', max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_check_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'compliance_check_results',
                'ordering': ['-created_at'],
            },
        ),
    ]
