# Generated by Django 4.2.7 on 2026-07-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0004_compliancecheckresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancecheckresult',
            name='is_ignored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='compliancecheckresult',
            name='location',
            field=models.CharField(blank=True, help_text='Where in the document this should be or was found', max_length=500),
        ),
        migrations.AddField(
            model_name='compliancerisk',
            name='location',
            field=models.CharField(blank=True, help_text='Where the problem is located in the text', max_length=500),
        ),
    ]
